[general]
OPENAI_API_KEY="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"
SERPER_API_KEY="b83616ff9617ab183686f267000793a427bf582c"

